#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
API=https://dnsapi.cn/Record.Ddns
CURRPATH=$(dirname $0)

# READ conf file
email=$(cat $CURRPATH/ddns_dnspod.conf | grep '^email=' | awk -F = '{print $2}')
password=$(cat $CURRPATH/ddns_dnspod.conf | grep '^password=' | awk -F = '{print $2}')
domain_id=$(cat $CURRPATH/ddns_dnspod.conf | grep '^domain_id=' | awk -F = '{print $2}')
record_id=$(cat $CURRPATH/ddns_dnspod.conf | grep '^record_id=' | awk -F = '{print $2}')
sub_domain=$(cat $CURRPATH/ddns_dnspod.conf | grep '^sub_domain=' | awk -F = '{print $2}')
full_domain=$(cat $CURRPATH/ddns_dnspod.conf | grep '^full_domain=' | awk -F = '{print $2}')

function main()
{
	new_ip=$(curl -sL http://agideo.com/ip?$full_domain)

	old_ip=$(ping -c 1 $full_domain|grep "PING" | sed -E 's/PING .* .([0-9.]+). .*/\1/g')

	if [ "$new_ip" != "$old_ip" ];
	then
      echo "$full_domain change to $new_ip"
      
	    msg=$(curl -sL -d "format=json&login_email=$email&login_password=$password&domain_id=$domain_id&record_id=$record_id&sub_domain=$sub_domain&record_line=默认" $API);
	fi
}

while true
do
  main
  sleep 60
done